services:
  frontend:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - $VIDEO_FOLDER:/videos
      - ./frontend:/var/www/frontend
    ports:
      - "$APP_PORT:80"
    depends_on:
      - backend
  backend:
    build: ./backend/
    restart: always
    stop_signal: SIGINT
    environment:
      - APP_ENV=production
      - APP_HOST=$APP_HOST
      - APP_PORT=$APP_PORT
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=5001
    volumes:
      - ./backend/:/app/backend
      - $VIDEO_FOLDER:/videos